services:
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  auth_service:
    build: .
    depends_on:
      - auth_db
    ports:
      - "8081:8081"
